help: 1
ability: 2
advancement: 3
alwaysday: 4
attribute: 5
ban: 6
ban-ip: 7
banlist: 8
bossbar
camerashake
changesetting
clear
clearspawnpoint
clone
connect
damage
data
datapack
daylock
debug
dedicatedwsserver
defaultgamemode
deop
dialogue
difficulty
effect
enchant
event
execute
experience
fill
fog
forceland
function
gamemode
gamerule
gametest
give
help
immutableword
item
jfr
kick
kill
list
locate
loot
me
mobevent
msg
music
op
ops
pardon
pardon-ip
particle
perf
permission
place
playanimation
playsound
oublish
recipe
reload
remove
replaceitem
ride
save
save-all
save-off
save-on
say
schedule
scoreboard
seed
setblock
setidletimeout
setmaxplayers
setworldspawn
spawnpoint
spectate
spreadplayer
stop
stopsound
structure
summon
tag
team
teammsg
teleport
tell
telldraw
testfor
testforblocks
tickingarea
time
title
titlera
tm
toggledownfall
tp
trigger
volumearea
w
wb
weather
whitelist
worldborder
worldbuildeer
wsserver
xp